//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema-lite";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type QueryLogFindManyArgs = $FindManyArgs<$Schema, "QueryLog">;
export type QueryLogFindUniqueArgs = $FindUniqueArgs<$Schema, "QueryLog">;
export type QueryLogFindFirstArgs = $FindFirstArgs<$Schema, "QueryLog">;
export type QueryLogExistsArgs = $ExistsArgs<$Schema, "QueryLog">;
export type QueryLogCreateArgs = $CreateArgs<$Schema, "QueryLog">;
export type QueryLogCreateManyArgs = $CreateManyArgs<$Schema, "QueryLog">;
export type QueryLogCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "QueryLog">;
export type QueryLogUpdateArgs = $UpdateArgs<$Schema, "QueryLog">;
export type QueryLogUpdateManyArgs = $UpdateManyArgs<$Schema, "QueryLog">;
export type QueryLogUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "QueryLog">;
export type QueryLogUpsertArgs = $UpsertArgs<$Schema, "QueryLog">;
export type QueryLogDeleteArgs = $DeleteArgs<$Schema, "QueryLog">;
export type QueryLogDeleteManyArgs = $DeleteManyArgs<$Schema, "QueryLog">;
export type QueryLogCountArgs = $CountArgs<$Schema, "QueryLog">;
export type QueryLogAggregateArgs = $AggregateArgs<$Schema, "QueryLog">;
export type QueryLogGroupByArgs = $GroupByArgs<$Schema, "QueryLog">;
export type QueryLogWhereInput = $WhereInput<$Schema, "QueryLog">;
export type QueryLogSelect = $SelectInput<$Schema, "QueryLog">;
export type QueryLogInclude = $IncludeInput<$Schema, "QueryLog">;
export type QueryLogOmit = $OmitInput<$Schema, "QueryLog">;
export type QueryLogGetPayload<Args extends $SelectIncludeOmit<$Schema, "QueryLog", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "QueryLog", Args, Options>;
