//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        QueryLog: {
            name: "QueryLog",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid") as FieldDefault
                },
                sql: {
                    name: "sql",
                    type: "String"
                },
                bind: {
                    name: "bind",
                    type: "String",
                    optional: true
                },
                explainPlan: {
                    name: "explainPlan",
                    type: "String",
                    optional: true
                },
                durationMs: {
                    name: "durationMs",
                    type: "Int"
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now") as FieldDefault
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
