import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode, Suspense } from 'react'

import { AppProvider } from 'util/provider/AppProvider'
import { HomeTimelineProvider } from 'util/provider/HomeTimelineProvider'
import { SuspenseProvider } from 'util/provider/SuspenseProvider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SuspenseProvider>
          <AppProvider>
            <Suspense>
              <HomeTimelineProvider>
                {children}
              </HomeTimelineProvider>
            </Suspense>
          </AppProvider>
        </SuspenseProvider>
      </body>
    </html>
  )
}
