// ============================================================
// Query IR — Execution Plan types
// ============================================================

import type { BindValue } from './nodes'

// --------------- Node output row type ---------------

/**
 * getIds ノードの出力行。
 * ID と時刻を常にペアで持ち、マージ・キャッシュの基本単位となる。
 */
export type NodeOutputRow = {
  id: number
  createdAtMs: number
}

// --------------- Execution Steps ---------------

/** Phase 1: ID collection step */
export type IdCollectStep = {
  type: 'id-collect'
  /** Source table name */
  source: string
  /** Generated SQL query (always SELECT id AS id, <timeCol> AS created_at_ms) */
  sql: string
  /** Bind parameters */
  binds: BindValue[]
  /** Optional time lower bound from another step */
  timeLowerBound?: {
    fromStep: number
    column: string
  }
}

/** Merge step for mixed queries (posts + notifications) */
export type MergeStep = {
  type: 'merge'
  strategy: 'interleave-by-time'
  /** Indices of preceding IdCollectStep to merge */
  sourceStepIndices: number[]
  limit: number
}

/** Phase 2: Detail data fetch */
export type DetailFetchStep = {
  type: 'detail-fetch'
  /** Target table type */
  target: 'posts' | 'notifications'
  /** SQL template with {IDS} placeholder */
  sqlTemplate: string
  /** Column index for reblog_of_post_id (for ID expansion) */
  reblogColumnIndex?: number
}

/** Phase 3: Batch enrichment */
export type BatchEnrichStep = {
  type: 'batch-enrich'
  /** Key: enrichment type (e.g. 'media', 'mentions'), Value: SQL template */
  queries: Record<string, string>
}

// --------------- Composite types ---------------

/** Union of all execution step types */
export type ExecutionStep =
  | IdCollectStep
  | MergeStep
  | DetailFetchStep
  | BatchEnrichStep

/** Complete execution plan */
export type ExecutionPlan = {
  steps: ExecutionStep[]
  meta: {
    /** What type of data this plan produces */
    sourceType: 'post' | 'notification' | 'mixed' | 'precomputed'
    /** Whether reblog expansion is needed in Phase 2 */
    requiresReblogExpansion: boolean
    /** Required batch query types */
    batchKeys: string[]
  }
}

// --------------- Compiler helper types ---------------

/** JOIN clause generated by the compiler */
export type JoinClause = {
  type: 'inner' | 'left'
  table: string
  alias: string
  on: string
}

/** Result of compiling a single filter node */
export type CompiledFilter = {
  /** WHERE clause fragment */
  sql: string
  /** Bind parameters */
  binds: BindValue[]
  /** Required JOIN clauses */
  joins: JoinClause[]
}
