name: Copilot Setup Steps

on: workflow_dispatch

env:
  COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: nextjs.org,storybook.js.org,vitest.dev,ui.shadcn.com,fonts.googleapis.com
  # Default environment variables for build
  NEXT_PUBLIC_APP_URL: 'http://localhost:3000'
  NEXT_PUBLIC_BACKEND_URL: 'https://pl.waku.dev'
  NEXT_PUBLIC_BACKEND_SNS: 'pleroma'

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Enable Corepack
        run: corepack enable
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn --immutable
